steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_TAG}"
      - "-f"
      - "deploy/Dockerfile.frontend"
      - "--build-arg=NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}"
      - "--build-arg=NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}"
      - "--build-arg=NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}"
      - "--build-arg=NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${_NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}"
      - "--build-arg=NEXT_PUBLIC_BACKEND_URL=${_NEXT_PUBLIC_BACKEND_URL}"
      - "."
images:
  - "${_TAG}"
substitutions:
  _TAG: ""
  _NEXT_PUBLIC_FIREBASE_API_KEY: ""
  _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ""
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: ""
  _NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ""
  _NEXT_PUBLIC_BACKEND_URL: ""
